language: ruby
rvm:
- 2.3.1
deploy:
  provider: heroku
  api_key:
    secure: DLpTZa25wFDmnntX+GB2rf4bDZEJnYqsAUvENa56u/BZ+/IqkAutoO1zfiXQV5UiJkGEBlb2I2I9+pDohzh6XIEVQjogRSbLetB5CJDYX98Ax3o6rPiBiq6tmtw+karQscWLLqwUdq34JEPgEKxxL3L1GoAGxbmlm7/QHfoEZqc5Gx6+nBDWDuMjUDKT7xXwhl2xcfaFWHPARCEBdUweTioUi24hMuj7zOXTcoooxVN91dWE8sLDTfa79YszgklKcfF9j7ZM5mCJoAri42AoMWuCDdS0t/4u7O5VeNrmzZfTD3svPJdMGaile0II+MuyetmQOgaNqWsXLBlSkVu8bgo/iRxZLLI/HBVvl3kMhdz6funUcB1sOnedUHtg6Y0PhT2mJ3EZXnZq+v2zDvrzR6sgtnKrzX0w8x8eTDhPJjVy6sTsETMdzVqpjEmnTzu/n0qvP013rxvbdR3p7HzpXWgELSrU2qYp96yiFYH5ap1GKChzzYE9bTQf2phtirdS45CXqo2+RdGPO9nRj5c8+QOox1Q1bJgHXpXIfK0uGNv57iOqqptCwo22S+L2eoc8RBvA24ta57DEW8IpAnm8jWD5eGbOZuPnhtxYG1B5qRvbs0I0yUvQ3lYO0YaaV4fImMNkCfUU8lP5frYVEY8IYHbFeexoiWClcCNa2R770qc=
  app: radiant-refuge-58204
  on:
    repo: mtetou/projet
    
addons:
    code_climate:
        repo_token: e797bb6064ab62774e50d05055c1ad6b3d45d201bd8b8f45e16b3ae12d9c2c5b


after_success:
  - bundle exec codeclimate-test-reporter