language: ruby
rvm:
- 2.0.0
- 1.9.3
- jruby-19mode
- rbx-2
deploy:
  provider: heroku
  api_key:
    secure: z9jGVzalKbTUfUzmc9zDH31ClW2X3lJQ8dLbvEHHtBphLB4zDDiut3IzHhVtuTZqowR0yusWFMui+A2svlUHl/Tehql2tuTj/ofjIc1n/SZgmSK45T+vHyAqrOJ4PfVmsyWjGnzemWepf5I4/H6Cwdz50isl/0s50w1R6SCLSwObzpzI8PDhzPpHs3DcySbT11I9SlKIu66iWnsba0lOgE8179DOppaNDyVa1zG/P/e6pLoSoFJkYIPjNm4bErHW97qCb931LpniRcIUPOwR3Un2zSDTJC2vDg3YQ+tCQbDD2yl11oYW64MtWPr4hRCpsLG7DYFjIONc9psDNiHZwilrJlS5t/qh9Rpqz8LrnfPFTsBQ7j6Uu5oIVZ8fjBC0JfBKMCvnPKIXTIjjvel9X0N6DOAz5l7eujPTruKXl7PUSW+xiqDrnEPFR/8Juzr2u8cTPMS1PgoXo29dLnyjY85TVvNp4xkZRC9cM9boX8W+6fK8RvjHx46NONjBbQ9AYsiXCKl82N3kMGetBHAqKUiJ7PyTUJaaP5wr0sv5YrSAzR+hCvIxwjsE3Ss/J55ki1NTB8azX2sfKUYQbPODFudta6jXCzuUTcSUQZItbjRp843VLahK3Giy6Ca2vldEx3m4mF7g9TraYFz86+D/bUq+/+SjMxAhbgt+OpU9QzM=
  app: radiant-refuge-58204
  on:
    repo: mtetou/projet
